feat(config): support replacement function for env var placeholders
go-kratos/kratos pull request #1135
Opened 2021-07-01 05:00 UTC by kagaya85

resolve #1065 

using go template lib to replace placeholder to environment variable

like this:
```yaml
http:
  server:
    # replace with env var "PORT" with default value 8080 
    port: {{ env "PORT" 8080 }}
    # replace with env var "TIMEOUT" without default value
    timeout: {{ env "TIMEOUT" }}
```

please help for code reviewing @ymh199478

thanks in advance :-)

2021-07-01 08:18 UTC, ymh199478 commented
200 行的单元测试看的真的好累，未来我们是否可以考虑改善一下单元测试

2021-07-01 11:04 UTC, kagaya85 commented
@ymh199478 感谢建议，现在的测试用例主要考虑覆盖 json/yaml 两种格式的配置，同时覆盖了不同值类型的配置项以及是否使用默认值等功能测试，可能略显冗余，可以考虑优化一下。

关于第二点，目前`TestFillTemplate`只测试了用环境变量填充占位符的功能，核心功能`env`暂时采用了匿名函数的方式实现，考虑到未来或许有其他的功能扩展，故没有使用如`FillWithEnvVar`等名称，如果需要，可以考虑进一步拆分功能与测试用例来使得名称更加细化明确。

再此感谢提议，欢迎继续讨论😃

2021-07-01 12:38 UTC, ymh199478 requested changes

2021-07-01 12:44 UTC, kagaya85 commented on config/config_test.go
> +			//t.Log(string(d))
已删除

2021-07-01 12:48 UTC, kagaya85 commented
是否需要rebase？

2021-07-01 12:51 UTC, ymh199478 commented
github有squash merge

2021-07-01 12:58 UTC, ymh199478 requested changes

2021-07-01 12:58 UTC, ymh199478 commented on config/config.go
> +			if val := os.Getenv(fmt.Sprint(args[0])); val != "" {
您需要处理空值和未设置值，因为有些环境变量就是被设定为空值
https://golang.org/pkg/os/#Getenv

2021-07-01 13:08 UTC, kagaya85 commented on config/config.go
> +			if val := os.Getenv(fmt.Sprint(args[0])); val != "" {
感谢提醒，也就是说对于用户有指定默认值的情况下，只有未设置值才使用默认值？

2021-07-01 13:19 UTC, ymh199478 commented on config/config.go
> +			if val := os.Getenv(fmt.Sprint(args[0])); val != "" {
是的，因为这是2个概念，一个是用户设定了值，但是值为空，另一个是用户没有设定值。

例如：如果为 redis 没有密码的实例给定一个空值，那么会引发错误。

2021-07-01 13:24 UTC, ymh199478 commented on config/config.go
> +			if val := os.Getenv(fmt.Sprint(args[0])); val != "" {
建议您添加一个测试用例，来保护这个行为

2021-07-01 13:27 UTC, ymh199478 commented
@shenqidebaozi 当前方案，没有达成 xml 的替换，所以配置替换是不完全的，在不做出大的修改的前提下，您有什么好的建议嘛？

2021-07-01 13:51 UTC, ymh199478 requested changes

2021-07-01 13:51 UTC, ymh199478 commented on config/config.go
> +				return "\"\""
啊，不要这样做，原先的做法就是对的，您现在改错了...

这表示的是一个叫：`""` 的字符串，字符内容是`"`

2021-07-01 13:56 UTC, kagaya85 commented on config/config.go
> +				return "\"\""
如果直接返回`""`，go template会把它处理为一个空串，这样就会出现类似下面的json：

```json
{"a": { "b": { "c": }}}
```
这会在后面Unmarshal时读取到`nil`值而报错，我认为我们期望得到一个`""`，而不是`nil`

2021-07-01 13:59 UTC, ymh199478 commented on config/config.go
> +				return "\"\""
json 应当这样给定：
```
{
    "foo": "{{ env "FOO" }}"
}
```

而非

```
{
    "foo": {{ env "PORT" 8080 }}
}
```

2021-07-01 14:02 UTC, kagaya85 commented on config/config.go
> +				return "\"\""
我理解了，感谢耐心解释

2021-07-01 14:17 UTC, kagaya85 commented
@ymh199478 是否意味着我们应该向用户建议使用env的地方都应该使用`""`，尽管当值为非空时不使用`""`也有相同的效果

对于开头的例子：
```yaml
http:
  server:
    # replace with env var "PORT" with default value 8080 
    port: "{{ env "PORT" 8080 }}"
    # replace with env var "TIMEOUT" without default value
    timeout: "{{ env "TIMEOUT" }}"
```

2021-07-01 14:20 UTC, ymh199478 commented
@kagaya85 我觉得并不是需要建议的，程序只是做了它原本做的事情，它很忠诚的替换了占位符不是吗？

2021-07-01 15:52 UTC, tonybase commented
foo: {{ env "foo.bar" }}
foo: {{ key "foo.bar" }}

也可以按 key 进行 resovle，或者 env、flag 都是可以的；
之前的想法时，env/flag 都会 merge 进来，最后都是根据key就可以了。

2021-07-01 23:54 UTC, ymh199478 commented
我赞同，加resolver是比较好的做法，decoder的职责就是从不同的源中得解析出数据，而resolver负责对占位符的解析，职责定义相对明确。

不过流程上多了一个步骤可能会发生bc，但是我觉得风险很小可以忽略。

—-

不过我有个疑问，因为方案是使用的模版，那么就有可能用户使用一些非预期的用法，例如：使用了模版的逻辑判断，这可能会导致解析故障。那么最好的做法则decoder之前完成解析。

2021-07-02 01:54 UTC, tonybase commented
> @tonybase 我赞同，加 resolver 是比较好的做法，decoder的职责就是从不同的源中得解析出数据，而resolver负责对占位符的解析，职责定义相对明确。
> 
> 使用统一 merge 进来的方法，就意味着配置自身可以引用自身配置了，在一些一线框架中也见到过有类似实现。
> 
> 不过我有个疑问，因为方案是使用的模版，所以可能用户会认为模板的全功能是可用的，那么用户可能会使用一些设计预期外的用法，例如：使用了模版的逻辑判断，这可能会导致 decoder 解析故障。那么能否在 decoder 之前完成占位符解析？
> 
> 还是说我们设计如此，不允许使用模板其他特性，并且只能在 value 值位置使用 placeholder

需要在 decoder 完成之后，会把一个个配置文件 merge 成kv结构，这时候才可以resolve到对应key。

2021-07-02 06:49 UTC, kagaya85 commented
@tonybase 大概了解，按我的理解我们目前需要对配置文件中的`key`和`env`以及启动参数`flag`进行merge形成最终的配置项，也就是说需要对decode并且merge后的配置做占位符替换：

```
multiple config source 
-> decode into map[string]interface{} 
-> merge 
-> resolve placeholder 
-> final config
```

简单思考后我有几个问题：

1. 是否可以不使用go template而仅仅通过字符串匹配和替换就可以实现我们需要的功能，目前看来go template的功能大部分不需要
2. env占位符通常直接写入配置文件中，我不太理解把env当作一个单独的配置来源，即`env.NewSource()`

我会重构一下代码，按resolver的方式实现，这个pr里先实现从配置文件的`key`和`env`中读取配置的功能，之后可以另开一个pr实现flag中的配置读取

2021-07-02 15:41 UTC, tonybase commented
> @tonybase 大概了解，按我的理解我们目前需要对配置文件中的`key`和`env`以及启动参数`flag`进行merge形成最终的配置项，也就是说需要对decode并且merge后的配置做占位符替换：
> 
> ```
> multiple config source 
> -> decode into map[string]interface{} 
> -> merge 
> -> resolve placeholder 
> -> final config
> ```
> 
> 简单思考后我有几个问题：
> 
> 1. 是否可以不使用go template而仅仅通过字符串匹配和替换就可以实现我们需要的功能，目前看来go template的功能大部分不需要
> 2. env占位符通常直接写入配置文件中，我不太理解把env当作一个单独的配置来源，即`env.NewSource()`
> 
> 我会重构一下代码，按resolver的方式实现，这个pr里先实现从配置文件的`key`和`env`中读取配置的功能，之后可以另开一个pr实现flag中的配置读取

我是怕有可能用户在配置中用了template，还有就方式是类似spring config placeholder:
${key:defaultValue}

也可以参考下 dotnet 的，用户其实也可以自己实现 Resolver

2021-07-03 13:41 UTC, ymh199478 commented
@kagaya85 目前我们讨论下来使用 `${key:defaultValue}` 的形式来实现。

现在需要添加一个 `resolve placeholder`  的步骤，默认情况下使用我们提供的占位符替换方法，但是用户可以自己实现自己的 resolver 来替换默认方法。

---

> env占位符通常直接写入配置文件中，我不太理解把env当作一个单独的配置来源，即env.NewSource()

env 作为 source，就意味着在读取 source 的时候将环境变量 merge 进 config。 `${key}` 除了可以加载环境变量外还可以引用其他 source 的配置。

---

除此之外，请问下您还有其他什么想法或是建议嘛？

2021-07-04 05:18 UTC, kagaya85 commented
感谢反馈，我这里还有几个细节的问题想确认一下：

1. > env 作为 source，就意味着在读取 source 的时候将环境变量 merge 进 config

这是否意味着可能存在另一个包含环境变量占位符的配置文件，如果指定`env.NewSource`，在加载配置时会在加载原始配置文件后加载包含占位符的配置文件，对该配置decode后进行resolve，再和原始配置进行merge。而原始配置来源，如`file.NewSource`，即使包含占位符也不做处理？

即 load -> decode -> 只对env来源的配置resolve -> merge

我原先的理解是应该对所有merge后的value值进行遍历，只要包含符合格式要求的占位符，那么就通过resolver处理，而不关心来自于哪个配置源，所以对`env.NewSource`这样的配置方式表示疑惑

即 load -> decode -> merge -> 对所有来源的配置resolve

需要确认下是以上那种方式

2. >  ${key} 除了可以加载环境变量外还可以引用其他 source 的配置

* 是否需要提供默认值的配置，类似：
```
${foo.bar:defaultValue}
```
* 如何区分key是引用其他source配置还是引用环境变量?
```
# 如何判断是读取环境变量foo还是引用其他source的foo
${foo}
```

3. resolver的实现细节

目前计划resolver按如下定义：
```go
// Resolver resolve placeholder in config.
type Resolver func(map[string]interface{}) error
```
* 需要传入merge后的map并直接对map进行值替换
* 内部实现递归对原map进行直接修改替换
* 考虑到要从map中获取某个具体字段的值，需要类似reader中Value函数的功能，重复实现可能会增加代码功能的冗余，不知道是否有什么好的建议

2021-07-04 05:35 UTC, ymh199478 commented
@kagaya85 

- 是按照你原先的理解，模式采用：`load -> decode -> merge -> 对所有来源的配置resolve`，先 merge 完所有的源，然后再进行占位符替换操作
- 需要 default value 的占位符替换机制
- 不需要判断key是引用其他 source 还是 环境变量，因为它直接从 merge 完的 map 中取值 （不用考虑占位符循环替换问题）。

2021-07-08 12:24 UTC, kagaya85 commented
@ymh199478 @tonybase Hi, 我重新实现了 resolver 来替换 merge map 中的的占位符，可以麻烦 review 一下是否合理？

用以读取 env 的 config source 我也实现了，目前来看，引入 resolver 或许是一个 break change，我认为需要改变当前 pr 的目标，专注于讨论 resolver 的实现方式，关于 env 以及之后的 flag 的实现可以另开 pr 讨论。

2021-07-09 07:00 UTC, ymh199478 commented
为什么觉得 resolver 是一个 bc 改动呢？是因为担心替换了占位符，导致一些上层逻辑发生改变嘛？

2021-07-09 07:25 UTC, kagaya85 commented
> 为什么觉得 resolver 是一个 bc 改动呢？是因为担心替换了占位符，导致一些上层逻辑发生改变嘛？

或许达不到bc的程度，不过需要更多的考虑可扩展性的问题，希望可以提供一些建议

2021-07-09 15:16 UTC, tonybase commented on config/config.go
> +	var resolve func(map[string]interface{}) error
直接返回匿名方法就可以了

2021-07-09 16:22 UTC, kagaya85 commented on config/config.go
> +	var resolve func(map[string]interface{}) error
`resolve`在98行需要递归调用处理`map[string]interface{}`，似乎不能使用匿名方法`resolve`在98行需要递归调用处理`map[string]interface{}`，似乎不能使用匿名方法`resolve`在98行需要递归调用处理`map[string]interface{}`，似乎不能使用匿名方法

2021-07-10 01:35 UTC, ymh199478 commented
现在我们对于占位符的提取将会是下面3种形式：`${VAR}`、`${VAR:default}`、`$VAR`

2021-07-10 13:45 UTC, tonybase commented on config/config.go
> +	var resolve func(map[string]interface{}) error
整理上看着没什么问题了，可以把 defaultResolver 和 defaultDecoder 都放在 options.go 下面的。

2021-07-10 15:58 UTC, kagaya85 commented
之后我会完善一下文档，下一步`EnvSource`的pr也会尽快提，十分感谢两位这几天的建议和帮助🙏

2021-07-10 16:01 UTC, tonybase approved these changes

2021-07-10 16:02 UTC, tonybase approved these changes

2021-07-10 16:03 UTC, merged