feat(env): add config env source
go-kratos/kratos pull request #1181
Opened 2021-07-13 13:29 UTC by kagaya85

resolve #1065, add new config source for reading environment variable

* Use `prefix` to filter the required variables
* Watching environment variables change are not support because I did not find a reasonable solution. Using `Watch` will block until `Stop` is called.
* When the env var loaded into the `KeyValue` struct, the `Format` field is nil, so when we decode it, we need to change it to `string` or we will get a base64 code when using `json.Unmarshal` to clone a map

2021-07-13 13:41 UTC, ymh199478 commented
测试用例增加不包含 `prefix` 的用例，不限制前缀也是一个有效行为

2021-07-13 14:17 UTC, ymh199478 requested changes

2021-07-13 14:17 UTC, ymh199478 commented on config/env/watcher.go
> +	return nil, fmt.Errorf("watcher stoped")
不应该引发 error，因为 `Stop` 是正常关闭

2021-07-13 14:35 UTC, ymh199478 commented on config/options.go
> +		target[src.Key] = string(src.Value)
此处可能会有副作用，我们需要看下有没有其他解决方案

2021-07-13 14:44 UTC, kagaya85 commented on config/env/env.go
> +	return
这里的返回值就是kv和err

2021-07-13 14:48 UTC, kagaya85 commented on config/options.go
> +		target[src.Key] = string(src.Value)
目前来看Format为空的情况只有env和之后的flag，两者的value均默认为string类型，理论上不会在转换时不会出现副作用
目前想到的可能有副作用的场景是value包含了二进制数据
当然最好的解决方法还是修改`cloneMap`的方式

2021-07-13 14:52 UTC, ymh199478 commented on config/env/env.go
> +	return
哦，我看到了，你直接覆盖了 kv

2021-07-13 17:20 UTC, tonybase commented on config/options.go
> +		target[src.Key] = string(src.Value)
这个感觉不应该转换的，可以在value那边获取时转换就可以了

2021-07-14 01:35 UTC, kagaya85 commented on config/options.go
> +		target[src.Key] = string(src.Value)
目前的`cloneMap`使用`marshalJson`的方式，该方式会导致value中的`[]byte`被编码为base-64

> Array and slice values encode as JSON arrays, except that []byte encodes as a base64-encoded string, and a nil slice encodes as the null JSON value.

如果不修改`cloneMap`的逻辑，我认为这里转换也是相对合理的

2021-07-14 02:42 UTC, tonybase commented on config/options.go
> +		target[src.Key] = string(src.Value)
那应该在cloneMap里面进行处理下，外部用户需要扩展，我们可以内部统一处理的

2021-07-14 05:03 UTC, tonybase approved these changes
LGTM

2021-07-14 05:06 UTC, ymh199478 approved these changes
LGTM

2021-07-14 05:10 UTC, merged