fix:update config and registry readme
go-kratos/kratos pull request #1393
Opened 2021-08-30 15:35 UTC by yuemoxi

#### Description (what this PR does / why we need it):

#### Which issue(s) this PR fixes:

fixes #

#### Other special notes for reviewer:

2021-08-30 15:51 UTC, kagaya85 requested changes

2021-08-30 15:51 UTC, kagaya85 commented on config/kubernetes/README.md
> +		KubeConfig:    filepath.Join(homedir.HomeDir(), ".kubernetes", "config"),
`.kube`是默认配置目录

2021-08-30 15:51 UTC, kagaya85 commented on config/README.md
> +## zookeeper
都使用大写开头？Zookeeper、Kubernetes

2021-08-30 15:51 UTC, kagaya85 commented on config/README.md
> +```
这里应该只有config？

2021-08-30 15:51 UTC, kagaya85 commented on config/kubernetes/example.go
> +				KubeConfig(filepath.Join(homedir.HomeDir(), ".kubernetes", "config")),
同上，应为`.kube`

2021-08-30 15:51 UTC, kagaya85 commented on config/kubernetes/watcher_test.go
> +	config, err := clientcmd.BuildConfigFromFlags("", filepath.Join(home, ".kubernetes", "config"))
同上

2021-08-30 15:52 UTC, yuemoxi commented on config/kubernetes/README.md
> +		KubeConfig:    filepath.Join(homedir.HomeDir(), ".kubernetes", "config"),
goland给我改的 没注意

2021-08-30 15:57 UTC, yuemoxi commented on config/README.md
> +## zookeeper
我看之前zookeeper 是小写的

2021-08-31 02:13 UTC, tonybase approved these changes

2021-08-31 02:13 UTC, merged