fix(registry/consul):fix update TTL problem
go-kratos/kratos pull request #1777
Opened 2022-01-18 09:29 UTC by Casper-Mars

#### Description (what this PR does / why we need it):
TTL-Check and TCP-Check cannot both be used at the same time. So this PR try to remove TTL-Check.

#### Which issue(s) this PR fixes (resolves / be part of):
fixes #1775

2022-01-19 10:42 UTC, Cluas submitted a review, later dismissed

2022-01-19 14:28 UTC, tonybase commented on contrib/registry/consul/client.go
> -			ticker := time.NewTicker(time.Second * time.Duration(c.healthcheckInterval))
healthcheckInterval 这个option是不是没用到了的

2022-01-19 14:54 UTC, Casper-Mars commented on contrib/registry/consul/client.go
> -			ticker := time.NewTicker(time.Second * time.Duration(c.healthcheckInterval))
有的，在上面用来控制Interval参数的

2022-01-19 14:55 UTC, Cluas commented on contrib/registry/consul/client.go
> -			ticker := time.NewTicker(time.Second * time.Duration(c.healthcheckInterval))
> 有的，在上面用来控制Interval参数的

tony 想说的是另一个 heartbeat 的 option

2022-01-19 14:56 UTC, Cluas commented on contrib/registry/consul/client.go
> -			ticker := time.NewTicker(time.Second * time.Duration(c.healthcheckInterval))
https://github.com/go-kratos/kratos/blob/f050b0743222712355077c830b8ba57508cea8be/contrib/registry/consul/registry.go#L30

2022-01-19 15:09 UTC, Casper-Mars commented on contrib/registry/consul/client.go
> -			ticker := time.NewTicker(time.Second * time.Duration(c.healthcheckInterval))
噢噢，这个option没有用了，我补一下吧

2022-01-20 01:37 UTC, haiyux approved these changes

2022-01-21 02:58 UTC, longXboy commented
是因为注册的时候灭有注册ttl的check导致的吧？

2022-01-21 02:58 UTC, longXboy requested changes
是因为注册的时候没有注册ttl的check导致的吧？不用删除ttl health check吧

2022-01-21 07:21 UTC, closed without merging