optimization:  protoc-gen-go-errors add comment
go-kratos/kratos pull request #1961
Opened 2022-04-27 18:00 UTC by JeffreyBool

protoc-gen-go-errors add comment

2022-04-28 03:50 UTC, tonybase approved these changes

2022-04-29 03:56 UTC, JeffreyBool commented
咋样，还有啥问题吗

2022-04-29 06:00 UTC, haiyux commented
lint 好像又问题 如果是mac/linux 可以执行一下 make fix 修一下

2022-04-29 08:33 UTC, Cluas commented on cmd/protoc-gen-go-errors/errors.go
> +func GetComment(camelValue, comment string) string {
GetComment -> buildComment

2022-04-29 08:43 UTC, Cluas approved these changes
LGTM. Thanks!

2022-04-29 08:45 UTC, haiyux approved these changes

2022-04-29 09:57 UTC, Cluas requested changes

2022-04-29 09:57 UTC, Cluas commented on cmd/protoc-gen-go-errors/errors.go
> +	return fmt.Sprintf("// %s %s", camelValue, comment)
I think this is an implicit behavior, the user should be responsible for his own Comment, not we generate a camelValue for it

2022-04-29 11:03 UTC, Cluas approved these changes

2022-04-30 07:08 UTC, haiyux approved these changes

2022-05-05 02:13 UTC, merged