feat: support polaris service governance
go-kratos/kratos pull request #2592
Opened 2022-12-20 07:08 UTC by shenqidebaozi

#### Description (what this PR does / why we need it):

#### Which issue(s) this PR fixes (resolves / be part of):

#### Other special notes for the reviewers:

2022-12-26 11:09 UTC, tonybase commented on contrib/polaris/config.go
> +func WithFileName(fileName string) ConfigOption {
func WithConfigFileGroup()
func WithConfigFileName()

2022-12-30 07:41 UTC, chuntaojun requested changes

2022-12-30 07:41 UTC, chuntaojun commented on contrib/polaris/registry.go
> +	if instance.ID == "" {
这个ID不要传，让北极星服务端自己生成

2022-12-30 07:41 UTC, chuntaojun commented on contrib/polaris/registry.go
> +					InstanceID:   split[i],
反注册不需要带上 InstanceID

2022-12-30 07:41 UTC, chuntaojun commented on contrib/polaris/registry.go
> +		GetInstancesRequest: model.GetInstancesRequest{
// 可选，是否跳过服务路由筛选，默认false
	SkipRouteFilter bool

把这个设置为 true，不要再发现的时候使用路由能力

2023-01-05 01:56 UTC, chuntaojun commented on contrib/polaris/config.go
> +// WithConfigNamespace with polaris config testNamespace
怎么改为 testNamespace 了？

2023-01-05 15:35 UTC, closed without merging